name: Run Scrapers

on:
  schedule:
    - cron: '0 08 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Legg til denne linjen
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v3  # Oppdater til v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Oppdater til v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run scrapers
        run: node scheduler.js
        env:
          NODE_ENV: production
          
      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update job data" || echo "No changes"
          git push